# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The knowledge through the experience!

email: arcangelilucia@gmail.com

description: "My projects experience BLOG"


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lucia1987.github.io"
twitter_username: lucia arcangeli
github_username:  Lucia1987

# Build settings
markdown: kramdown
